import { CATEGORIES } from "@/lib/constants";
import type { Post } from "@/lib/types";

const at = (day: number) => `2026-08-${String(day).padStart(2, "0")}T08:00:00.000Z`;

export const DEMO_POSTS: Post[] = [
  {
    id: "preview-1",
    title: "Hạ tầng AI đang thay đổi cách chúng ta thiết kế sản phẩm số",
    slug: "ha-tang-ai-va-san-pham-so",
    excerpt: "Từ mô hình nhỏ chạy tại thiết bị đến trung tâm dữ liệu hiệu quả hơn, làn sóng AI mới đang đi vào từng lớp của trải nghiệm số.",
    content: "## Hạ tầng thông minh hơn\n\nCác nhóm sản phẩm đang quan tâm nhiều hơn đến **hiệu quả**, khả năng kiểm soát dữ liệu và trải nghiệm thực sự hữu ích. Đây là bài viết mẫu để thể hiện nhịp điệu đọc của giao diện.\n\n> Nội dung thật sẽ được quản trị viên xuất bản từ Supabase.",
    thumbnail_url: null,
    author_name: "Ban biên tập",
    category: CATEGORIES[0],
    status: "published",
    created_at: at(12),
    updated_at: at(12),
    published_at: at(12),
  },
  {
    id: "preview-2",
    title: "Không gian làm việc lai và những thiết bị thực sự đáng cân nhắc",
    slug: "khong-gian-lam-viec-lai",
    excerpt: "Một máy tính linh hoạt chưa đủ: trải nghiệm làm việc tốt hơn bắt đầu từ cách thiết bị, phần mềm và thói quen gặp nhau.",
    content: "# Không gian làm việc lai\n\nĐây là nội dung trình bày mẫu bằng Markdown.",
    thumbnail_url: null,
    author_name: "Mai An",
    category: CATEGORIES[3],
    status: "published",
    created_at: at(10),
    updated_at: at(10),
    published_at: at(10),
  },
  {
    id: "preview-3",
    title: "Điện thoại năm nay: nhỏ hơn ở những điều không cần thiết",
    slug: "dien-thoai-va-nhung-thay-doi-nho",
    excerpt: "Thiết kế gọn gàng, phần mềm ít gây xao nhãng và máy ảnh hiểu ngữ cảnh là ba xu hướng đang định hình nhóm thiết bị cá nhân.",
    content: "# Thiết bị cá nhân\n\nNội dung sẽ được thay bằng bài viết do quản trị viên đăng.",
    thumbnail_url: null,
    author_name: "Thu Hà",
    category: CATEGORIES[2],
    status: "published",
    created_at: at(8),
    updated_at: at(8),
    published_at: at(8),
  },
  {
    id: "preview-4",
    title: "Mạng lưới cảm biến giúp khoa học quan sát thế giới tinh vi hơn",
    slug: "mang-luoi-cam-bien-khoa-hoc",
    excerpt: "Khi cảm biến rẻ hơn và dữ liệu giàu ngữ cảnh hơn, nhiều câu hỏi khoa học cũ đang có cơ hội được trả lời theo cách mới.",
    content: "# Quan sát và dữ liệu\n\nMỗi bài viết có thể được biên soạn bằng Markdown trong trang quản trị.",
    thumbnail_url: null,
    author_name: "Linh Chi",
    category: CATEGORIES[1],
    status: "published",
    created_at: at(5),
    updated_at: at(5),
    published_at: at(5),
  },
  {
    id: "preview-5",
    title: "Thiết kế số sau thời kỳ của những màn hình giống nhau",
    slug: "thiet-ke-so-va-trai-nghiem-moi",
    excerpt: "Cá tính thương hiệu không chỉ nằm ở màu sắc; nó nằm ở nhịp chuyển cảnh, khoảng trắng và những chi tiết giúp người đọc ở lại lâu hơn.",
    content: "# Thiết kế số\n\nBài viết mẫu cho thẻ tin tức.",
    thumbnail_url: null,
    author_name: "Quang Minh",
    category: CATEGORIES[4],
    status: "published",
    created_at: at(3),
    updated_at: at(3),
    published_at: at(3),
  },
  {
    id: "preview-6",
    title: "Chiếc máy tính cá nhân quay lại với vai trò trung tâm",
    slug: "may-tinh-ca-nhan-tro-lai",
    excerpt: "Khi nhiều tác vụ sáng tạo cần sức mạnh cục bộ, chiếc máy tính để bàn và laptop chuyên dụng đang có một vòng đời mới.",
    content: "# Máy tính cá nhân\n\nBài viết mẫu cho phần danh sách mới nhất.",
    thumbnail_url: null,
    author_name: "Nguyên Khôi",
    category: CATEGORIES[3],
    status: "published",
    created_at: at(1),
    updated_at: at(1),
    published_at: at(1),
  },
];
